### ISSUE TITLE
Do you plan to release this for F41?

### ISSUE THREAD

**Issue by bsherman** [negativo17/libvdpau#1]
@scaronni after https://github.com/negativo17/evdi-kmod/issues/2 was closed I was looking the Universal Blue tracker and saw we still don't have `libvdpau` on F41.

I read your [blog post](https://negativo17.org/prime-optimus-laptops-and-multi-gpu-systems/) and saw your comment:
> VDPAU is pretty much dead, there is no support for Optimus/Prime laptops and no support for Wayland.

So I wouldn't be surprised if you intentionally chose to not build this for F41 given the move the Wayland only.

**Comment by scaronni** [comment]
`libvdpau` is shipping in the main Fedora repositories: https://koji.fedoraproject.org/koji/buildinfo?buildID=2497153

I'm shipping it in the Nvidia/Multimedia repository because at one point there were changes compared to what was available compared to the distribution; for example when 1.4 was shipping and 1.5 was available with AV1 acceleration support. EL8 still ships only 1.4.

As of now, the only difference compared to the one in the distribution is the AV1 tracing support commit. I think I'll just add that to the Fedora packages and drop it from my repositories for Fedora 39+.

But yes, it's basically dead, works on X only and is no longer being developed.

**Comment by bsherman** [comment]
> But yes, it's basically dead, works on X only and is no longer being developed.

This alone is reason enough to not worry about it from Universal Blue's perspective as we intend to follow Fedora's Wayland-only lead.

**Comment by scaronni** [comment]
Anyway, I've pushed the tracing patch also to Fedora builds, when the update goes live I'll remove `libvdpau` from the Fedora repositories.
